// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.omg.stub.java.lang;

import java.io.Serializable;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.rmi.UnexpectedException;
import javax.rmi.CORBA.Stub;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.RemarshalException;
import org.omg.CORBA.portable.ServantObject;

public class _Cloneable_Stub extends Stub implements Cloneable,
Remote {
    
    private static final String[] _type_ids = {
        "RMI:java.lang.Cloneable:0000000000000000"
    };
    
    public String[] _ids() { 
        return _type_ids;
    }
}
