// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.ibm.websphere.csi;

import java.io.Serializable;
import java.rmi.Remote;
import java.rmi.RemoteException;
import java.rmi.UnexpectedException;
import javax.rmi.CORBA.Stub;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.RemarshalException;
import org.omg.CORBA.portable.ServantObject;

public class _TransactionalObject_Stub extends Stub implements TransactionalObject {
    
    private static final String[] _type_ids = {
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public String[] _ids() { 
        return _type_ids;
    }
}
